wallpaper {
    monitor = eDP-1
    path = $HOME/Pictures/Wallpapers/current-wallpaper
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = $HOME/Pictures/Wallpapers/
    recursive = true
    fit_mode = cover
    timeout = 3600
}
