# Swaybar status bar config
# Read `man 5 sway-bar` for more information about this section.

# Gruvbox color pallete
set $bg        #282828
set $bg_alt    #3c3836
set $bg_2      #504945
set $fg        #ebdbb2
set $fg_dim    #d5c4a1
set $fg_soft   #a89984

set $yellow    #d79921
set $red       #cc241d
set $blue      #458588

bar {
    id 0
    position top
    mode dock
    font $font

    gaps $gap
    separator_symbol |
    workspace_buttons yes

    tray {
        icon_theme $icontheme
    }

    # When the status_command prints a new line to stdout, swaybar updates.
    # The default just shows the current date and time.
    status_command i3blocks

    colors {
        # General bar colors
        background  $bg
        statusline  $fg_dim
        separator   $bg_2

        focused_workspace  $yellow  $bg      $fg
        active_workspace   $bg_2    $bg_alt  $fg
        inactive_workspace $bg_alt  $bg      $fg_soft
        urgent_workspace   $red     $bg      $fg
    }
}
