# Color pallete and theme


# See https://github.com/morhetz/gruvbox-contrib/blob/master/color.table
# Gruvbox base
set $bg        #282828
set $bg_alt    #3c3836
set $bg_2      #504945
set $fg        #ebdbb2
set $fg_dim    #d5c4a1
set $fg_soft   #a89984

# Accents
set $red       #cc241d
set $green     #98971a
set $yellow    #d79921
set $blue      #458588
set $purple    #b16286
set $aqua      #689d68

set $dark      #1d2021


# Class                 border   bground  text     indicator  child_border
client.focused          $yellow  $bg      $fg      $yellow    $yellow
client.focused_inactive $bg_2    $bg_alt  $fg_dim  $bg_2      $bg_2
client.unfocused        $bg_alt  $bg      $fg_soft $bg_alt    $bg_alt
client.urgent           $red     $dark    $fg      $red       $red
client.placeholder      $dark    $dark    $fg_soft $dark      $dark
